title: "Policy Clustering"
remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
include: ["_pages"]
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false
